### ISSUE TITLE
Waiting for Restock

### ISSUE THREAD

**Issue by fostermatt** [natewong1313/bird-bot#46] opened 2020-05-01 00:18 UTC
Even for items that are in stock on the website I get the same message. 

I had the "add to cart" bug for best buy so I decided to add an item I knew they had in stock to see if I could reproduce the bug. No matter the item I added the bot will continually say it's waiting for stock. Is there a way I can can dig in further tosee what's going on?

**Comment by RealScatman** [comment] 2020-05-01 11:33
The problem is that the SKU_ID for the product is not being fetched properly - which in turn breaks the check_stock function for BestBuy.  This is an easy fix - just fetch the proper index of the target data value that holds the SKU_ID. ( I have fixed it in my own instance of the application)

**Comment by fostermatt** [comment] 2020-05-01 20:38
> The problem is that the SKU_ID for the product is not being fetched properly - which in turn breaks the check_stock function for BestBuy. This is an easy fix - just fetch the proper index of the target data value that holds the SKU_ID. ( I have fixed it in my own instance of the application)

Sounds awesome, could you give me a walkthrough on how to fix that? Just a pointer on which file to look at would be great. I tried searching the repo for "SKU_ID" and couldnt' find anything.

**Comment by dedevelopersltd** [comment] 2020-05-01 20:56
I am having issue when payment submits its asked for captcha and don't let me go through, do you know how to solve captcha issue?

**Comment by mahevstark** [comment] 2020-05-01 21:04
I've got the solution, I cannot provide any hints until any of you listens and fixes my problem, on getting checkout data step, I'm facing captcha, I've decided to use anticaptcha library to solve this, but looking in inspect, the walmart somehow encrypts captcha's response before sending it to their server... I need to know how to encrypt that. 
Steps to produce:

1. open walmart, add anything to cart, checkout with fake details submit order
2. keep repeating until you get captcha (don't forget to open network console first to check requests and responses)
3. when you solve captcha you'll see a response labeled as "unverifiy" from google, that contains a long string
4. now in next request walmart submits data to their servers see "bundle" request, check the request it sent, it sends different string... REAL QUESTION, how? how that string got changed?

**Comment by RealScatman** [comment] 2020-05-01 21:59
sites/bestbuy.py 
update the following line:
self.sku_id = doc.xpath('//span[@class="product-data-value body-copy"]/text()')[1].strip()
to:
self.sku_id = doc.xpath('//span[@class="product-data-value body-copy"]/text()')[2].strip()

**Comment by RealScatman** [comment] 2020-05-01 22:08
> I am having issue when payment submits its asked for captcha and don't let me go through, do you know how to solve captcha issue?

this is an entirely different issue and should be added as a seperate issue.  This is not the place to post an issue about recaptcha.

**Comment by RealScatman** [comment] 2020-05-01 22:09
> > The problem is that the SKU_ID for the product is not being fetched properly - which in turn breaks the check_stock function for BestBuy. This is an easy fix - just fetch the proper index of the target data value that holds the SKU_ID. ( I have fixed it in my own instance of the application)
> 
> Sounds awesome, could you give me a walkthrough on how to fix that? Just a pointer on which file to look at would be great. I tried searching the repo for "SKU_ID" and couldnt' find anything.

sites/bestbuy.py
update the following line:
`self.sku_id = doc.xpath('//span[@class="product-data-value body-copy"]/text()')[1].strip()`
to:
`self.sku_id = doc.xpath('//span[@class="product-data-value body-copy"]/text()')[2].strip()`

**Comment by fostermatt** [comment] 2020-05-01 22:21
> > > The problem is that the SKU_ID for the product is not being fetched properly - which in turn breaks the check_stock function for BestBuy. This is an easy fix - just fetch the proper index of the target data value that holds the SKU_ID. ( I have fixed it in my own instance of the application)
> > 
> > 
> > Sounds awesome, could you give me a walkthrough on how to fix that? Just a pointer on which file to look at would be great. I tried searching the repo for "SKU_ID" and couldnt' find anything.
> 
> sites/bestbuy.py
> update the following line:
> `self.sku_id = doc.xpath('//span[@class="product-data-value body-copy"]/text()')[1].strip()`
> to:
> `self.sku_id = doc.xpath('//span[@class="product-data-value body-copy"]/text()')[2].strip()`

Thanks. Got that issue resolved now I'm just looking at the "Adding To Cart" freeze. =P

Have you had the same problem with Walmart links? I have but don't see sku_id refrenced in that file at all

**Comment by RealScatman** [comment] 2020-05-02 16:30
> > > > The problem is that the SKU_ID for the product is not being fetched properly - which in turn breaks the check_stock function for BestBuy. This is an easy fix - just fetch the proper index of the target data value that holds the SKU_ID. ( I have fixed it in my own instance of the application)
> > > 
> > > 
> > > Sounds awesome, could you give me a walkthrough on how to fix that? Just a pointer on which file to look at would be great. I tried searching the repo for "SKU_ID" and couldnt' find anything.
> > 
> > 
> > sites/bestbuy.py
> > update the following line:
> > `self.sku_id = doc.xpath('//span[@class="product-data-value body-copy"]/text()')[1].strip()`
> > to:
> > `self.sku_id = doc.xpath('//span[@class="product-data-value body-copy"]/text()')[2].strip()`
> 
> Thanks. Got that issue resolved now I'm just looking at the "Adding To Cart" freeze. =P
> 
> Have you had the same problem with Walmart links? I have but don't see sku_id refrenced in that file at all

I have also fixed the walmart restock issue as well ,(but that should be opened and addressed as a seperate issue, for tracking purposes.) Please open an issue tracker for walmart restock issue and the issue can be addressed and documented/resovled there.

**Comment by RealScatman** [comment] 2020-05-02 16:31
This issue should be marked as closed once my code fix (referenced above) is merged with master branch.

**Closed as completed** 2020-05-02 22:31 UTC

**Comment by R1fast** [comment] 2020-11-12 21:21
Not sure if the author or anyone is still supporting this bot but a seperate [bug 57](https://github.com/natewong1313/bird-bot/issues/57) was filed for Walmart as this is still occurring (as of 11/12/20 for PS5 launch day)  I wasn't able to figure this out myself - would be great if anyone who has the skills can help.

PS 5 launch day and all!!
